---
- name: check if mongo already installed
  stat: path=/usr/bin/mongo
  register: mongo_bin
  
- name: check if mongo already installed
  shell: mongod --version | grep 'db version' | cut -d' ' -f3
  when: mongo_bin.stat.exists == True
  register: mongo_version

- name: Add an apt key by id from a keyserver
  apt_key: 
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 7F0CEB10
  become: true
  when: (mongo_version is undefined) or (mongo_version != 'v2.4.14')
  
- name: Add mongodb community edition repo 
  apt_repository:
    repo: deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen
    state: present
    filename: 'mongodb.ce.v24.list'
  become: true
  when: (mongo_version is undefined) or (mongo_version != 'v2.4.14')

- name: update the apt get 
  apt: 
    update_cache: yes
  become: true
  when: (mongo_version is undefined) or (mongo_version != 'v2.4.14')

- name: install mongodb community edition v2.4
  apt: 
    name: mongodb-10gen
    state: present
  become: true
  when: (mongo_version is undefined) or (mongo_version != 'v2.4.14')
