---
# file: roles/aws/mongo.replicaset/tasks/main.yml
- name: create AWS EC2 instance and volume for a 3 server replicaset
  include: '../../roles/aws/common/tasks/create.instance.with.volume.yml'
  vars:
    instance_name: "{{ rs_item }}"
    server_group_name: "{{ replica_set_name }}"
  with_items:
    - "{{ replica_set_name }}-svr1"
    # - "{{ replica_set_name }}-svr2"
    # - "{{ replica_set_name }}-svr3"
  loop_control:
    loop_var: rs_item

# - name: create AWS EC2 instances for a 3 server replicaset
#   include: '../../roles/aws/common/tasks/set.tags.on.instance.volumes.yml'
#   vars: 
#     instance_id: "{{ item }}"
#     instance_name: "{{ item }}"
#   with_items:
#     - "i-003f407b037d0183f"
