---
- name: create AWS instance
  include: "../../../../../roles/aws/tasks/create.instance.yml"

- name: display the output of create.instance
  debug: msg="created EC2 instance - '{{ create_output }}'"

- name: wait for SSH to be available on machine
  include: "../../../../../roles/system/tasks/wait.for.ssh.yml"
  with_items: "{{ create_output.instances }}"
  loop_control:
    loop_var: ssh_instance_item

- name: set the tags on attached volumes for each instance
  include: "../../../../../roles/aws/tasks/set.tags.on.instance.volumes.yml"
  with_items: "{{ create_output.instances }}"
  loop_control:
    loop_var: instance_item

- name: yum upgrade on server
  include: "../../../../../roles/system/tasks/yum.upgrade.yml"
  with_items: "groups.{{ server_group_name }}"