---
- name: generate member certificates
  hosts: local
  tasks:
    - name: generate script file for member certificate using template file
      template:
        src: '{{ template_dir }}/certificates/generate.member.certificate.txt'
        dest: '{{ output_dir }}/scripts/certificates/generate.certificate.{{ item }}.sh'
        mode: 0744
      with_items:      
        - ska-av-demo-0.ska-personal.4870.mongodbdns.com
        - ska-av-demo-1.ska-personal.4870.mongodbdns.com
        - ska-av-demo-2.ska-personal.4870.mongodbdns.com
        - mongodb_monitoring_agent
        - mongodb_automation_agent
        - mongodb_backup_agent
        
#    - name: run the root certificate authority generated file 
#      shell: '{{ output_dir }}/scripts/certificates/generate.root.certificate.authority.sh'
