---
- name: upload generated certificates to servers 
  hosts: certificate_servers
  tasks: 
    - name: move the rootCA.pem file 
      copy:
        src: '{{ output_dir }}/certs/rootCA.pem'
        dest: /etc/ssl/rootCA.pem
        owner: mongod
        group: mongod
      become: true 

    - name: move the agent pem files 
      copy:
        src: '{{ output_dir }}/certs/{{item}}.pem'
        dest: /etc/ssl/{{item}}.pem
        owner: mongod
        group: mongod
      become: true 
      with_items:
        - mongodb_monitoring_agent
        - mongodb_automation_agent
        - mongodb_backup_agent

    - name: move the server pem files 
      copy:
        src: '{{ output_dir }}/certs/{{ansible_ssh_host}}.pem'
        dest: /etc/ssl/{{ansible_ssh_host}}.pem
        owner: mongod
        group: mongod
      become: true 
