---

- name: check if data folder already exists
- stat: 
    path: /data
  register: check_folder

- name: make ext4 device for holding db data
  shell: 'mkfs.xfs /dev/xvdb'
  become: true
  when: check_folder.stats.exists == False

- name: create data folder 
  file:
    path: /data
    mode: 0755
    state: directory
  become: true
  when: check_folder.stats.exists == False

- name: mount xvdb device as data folder
  mount:
    path: /data
    src: /dev/xvdb
    fstype: xfs
    opts: noatime
    state: present
  become: true
  when: check_folder.stats.exists == False