---

- name: check if log folder already exists
- stat: 
    path: /data/log
  register: check_folder

- name: make ext4 device for holding log data
  shell: 'mkfs.ext4 /dev/xvdc'
  become: true
  when: check_folder.stats.exists == False

- name: create data folder 
  file:
    path: /data/log
    mode: 0755
    state: directory
  become: true
  when: check_folder.stats.exists == False

- name: mount xvdc device as log folder
  mount:
    path: /data/log
    src: /dev/xvdc
    fstype: ext4
    opts: noatime
    state: present
  become: true
  when: check_folder.stats.exists == False