---
# - name: install python v2.7 dependencies for automation
#   hosts: mongod_demo
#   roles: 
#     - roles/common/tasks/yum.install.python.yml

- name: create xfs device and mount it as data  
  hosts: mongod_demo
  roles: 
    # - "roles/common/tasks/yum.install.xfstools.yml"
    - "roles/common/tasks/mount.data.device.yml"
    # - roles/common/tasks/mount.journal.device.yml
    # - roles/common/tasks/mount.log.device.yml

# - name: create mongod v3.0 replica set on Amazon Linux 
#   hosts: mongod_demo
#   roles: 
#     - roles/mongod/install/amazon/ce.v30/
    
# - name: copy mongod config file to server
#   hosts: mongod_demo
#   vars:
#     - mongo_port: 27017
#     - db_dir: ''
#     - replicaset_name: rsOsmal
#     - mongod_conf: '{{local_root_dir}}/roles/mongod/install/amazon/ce.v30/files/mongod.conf'
#     - address_mappings: 
#         - {public: 'ec2-54-245-71-119.us-west-2.compute.amazonaws.com', internal: 'ip-172-31-9-215.us-west-2.compute.internal'}
#         - {public: 'ec2-54-149-90-102.us-west-2.compute.amazonaws.com', internal: 'ip-172-31-12-46.us-west-2.compute.internal'}
#         - {public: 'ec2-54-245-128-177.us-west-2.compute.amazonaws.com', internal: 'ip-172-31-13-198.us-west-2.compute.internal'}
#   roles: 
#     - roles/common/tasks/copy.file.mongod.conf.yml