---
- name: check if mongo already installed
  stat: path=/usr/bin/mongo
  register: mongo_bin
  
- name: check mongod version number
  shell: mongod --version | grep 'db version' | cut -d' ' -f3
  when: mongo_bin.stat.exists == True
  register: mongo_version

- name: Add mongodb community edition repo 
  yum_repository: 
    name: mongodb-org-3.0
    file: mongodb-org-3.0
    description: MongoDB Repository
    baseurl: https://repo.mongodb.org/yum/amazon/2013.03/mongodb-org/3.0/x86_64/
    gpgcheck: no
    enabled: yes
  become: true
  when: (mongo_version is undefined) or (mongo_version != 'v3.0.14')
  
- name: update the yum 
  yum:
    name: '*'
    state: latest
  become: true
  when: (mongo_version is undefined) or (mongo_version != 'v3.0.14')

- name: install mongodb community edition v3.0
  yum: 
    name: mongodb-org
    state: present
  become: true
  when: (mongo_version is undefined) or (mongo_version != 'v3.0.14')
