---
- name: yum upgrade on server
  include: "./yum.upgrade.yml"

- name: yum install XFS 
  include: "./yum.install.xfstools.yml"

- name: ensure xvdb device is XFS and mounted
  include: "./mount.data.device.yml"

- name: disable selinux and restart
  include: "./disable.selinux.yml"

- name: reboot the server
  include: "./reboot.yml"