---
# file: roles/system/tasks/mount.data.device.yml
- name: format xvdb volume
  filesystem:
    fstype: xfs
    dev: /dev/xvdb
    opts: -cc
  become: true

- name: mount the device as data
  mount:
    path: /data
    src: /dev/xvdb
    fstype: xfs
    opts: noatime
    state: present
  become: true
