---
- name: check if mongo already installed
  stat: 
    path: /usr/bin/mongo
  register: mongo_bin

- name: check mongod version number
  shell: mongod --version | grep 'db version' | cut -d' ' -f3 
  when: (mongo_bin.stat.exists == True)
  register: mongo_version

- debug: msg="mongo_version {{mongo_version}}"

- name: Add mongodb community edition repo 
  yum_repository: 
    name: "mongodb-{{mongo_major_version}}"
    file: "mongodb-{{mongo_major_version}}"
    description: MongoDB Repository
    baseurl: http://downloads-distro.mongodb.org/repo/redhat/os/x86_64/
    gpgcheck: no
    enabled: yes
  become: true
  register: add_repo
#  when: (mongo_version is undefined) or (mongo_version != "v2.4.14")
  
- debug: msg="add_repo {{add_repo}}"


# - name: update the yum 
#   yum:
#     name: '*'
#     state: latest
#   become: true
#   when: (mongo_version is undefined) or (mongo_version != 'v2.4.14')

- name: install mongodb community edition {{mongo_full_version}}
  yum: 
    name: "{{item}}-{{mongo_full_version}}"
    state: present
    exclude: "mongodb-org,mongodb-org-server"
  become: true
  with_items: 
    - "mongo-10gen"
    - "mongo-10gen-server"
  #  when: (mongo_version is undefined) or (mongo_version != '2.4.14')
