---
- name: create AWS instance
  include: "../../roles/aws/common/tasks/create.instance.yml"

- name: display the output of create ec2 instance
  debug: msg="created EC2 instance - '{{ ec2result }}'"

- name: wait for SSH to be available on machine
  include: "../../roles/aws/common/tasks/wait.for.ssh.yml"
  with_items: "{{ ec2result.instances }}"
  loop_control:
    loop_var: ssh_instance_item

- name: Set the tags on attached volumes for each instance
  include: "../../roles/aws/common/tasks/set.tags.on.instance.volumes.yml"
  with_items: "{{ ec2result.instances }}"
  loop_control:
    loop_var: instance_item
