---

- name: print the vars from higher level tasks
  debug: msg="{{ replica_set_name }} {{ rs_item }}"

- name: create an AWS EC2 instance and attach volume
  ec2:
     key_name: "{{ aws_security_key }}"
     region: "{{ aws_region }}"
     zone: "{{ aws_availability_zone }}"
     group: "{{ aws_security_group }}"
     instance_type: "{{ aws_instance_type }}"
     image: "{{ aws_ami }}"
     wait: yes
     instance_tags:
       "Name": "{{ rs_item }}"
       "owner": "{{ aws_tag_owner }}"
       "expire-on": "{{ aws_tag_expireon }}"
     count: 1
     volumes:
       - device_name: /dev/sda1
         volume_type: gp2
         volume_size: 10
         delete_on_termination: true
       - device_name: /dev/xvdb
         volume_type: gp2
         volume_size: 30
         delete_on_termination: true
  register: ec2result

# - name: Add the newly created EC2 instance(s) to the local host group (located inside the directory)
#   local_action: lineinfile 
#                 dest="../../hosts" 
#                 regexp={{ item.public_ip }} 
#                 insertafter="[{{ server_group_name }}]" line={{ item.public_ip }}
#   with_items: {{ ec2result.instances }} 
