---
ami: "{{ redhat_ami }}"
instance_type: "t2.micro"
tag_expireon: "2018-02-28"
data_vol_size: 60
tag_name: "ska"
group_name: "rs"

server_number: 1
instance_name: "{{ tag_name }}_{{ group_name }}_{{ server_number }}"
server_group_name: "{{ tag_name }}_{{ group_name}}"
ssh_user: "ec2-user"
tag_owner: "shyam.arjarapu"


##################
# IMPORTANT:
##################
region: "us-west-2"
security_key: "ska-play"
security_group: "ska-sg-aws"
redhat_ami: "ami-9fa343e7"


availability_zone: "{{ region }}c"
create_data_folder: True
data_folder: "/app/mongodb"
swap_location: /etc/xvdf

# ami instances 
# redhat_ami: "ami-9fa343e7" # us-west-2