---
- name: install and configure mongodb in replicaset instances
  hosts: "ska_poc_iop"
  roles:
    - role: mongo
      mongo_version: "3.6.2"
      tag_name: "ska_poc"
      group_name: "iop"
      replset_name: "rs0"
