---
    
- name: set vm.swappiness to 60
  become: true
  sysctl:
    name: vm.swappiness
    value: 60
    state: present
    sysctl_set: yes

- name: set vm.vfs_cache_pressure to 100
  become: true
  sysctl:
    name: vm.vfs_cache_pressure
    value: 100
    state: present
    sysctl_set: yes

- name: set net.ipv4.tcp_keepalive_time timeout to 120
  become: true
  sysctl:
    name: net.ipv4.tcp_keepalive_time
    value: 120
    state: present
    sysctl_set: yes

- name: set kernel.pid_max to max 64000
  become: true
  sysctl:
    name: kernel.pid_max
    value: 64000
    state: present
    sysctl_set: yes

- name: set kernel.threads-max to max 64000
  become: true
  sysctl:
    name: kernel.threads-max
    value: 64000
    state: present
    sysctl_set: yes

- name: set fs.file-max to max 98000
  become: true
  sysctl:
    name: fs.file-max
    value: 98000
    state: present
    reload: yes
    sysctl_set: yes

- name: disable selinux
  become: true
  selinux:
    state: disabled
    policy: targeted

- name: reboot
  become: true
  shell: (sleep 1 && /usr/sbin/reboot &)
  ignore_errors: true
  async: 1
  poll: 0

- name: wait for ssh
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    delay: 10
    timeout: 300
    state: started
  connection: local

