---

- name: add mongodb-{{ mongo_version[0:3] }} to yum repo 
  become: true
  yum_repository: 
    name: "mongodb-org-{{ mongo_version[0:3] }}"
    description: MongoDB Repository
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/3.4/x86_64/
    gpgcheck: yes
    enabled: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-3.4.asc
    state: present

- name: install mongodb ce {{ mongo_version }}
  become: true
  yum: 
    name: "mongodb-org-{{ mongo_version }}"
    state: present
