---
## file: playbooks/ska.awsl/setup.servers.yml
- name: yum packages on shard hosts
  hosts: "{{ server_group_name }}"
  roles: 
    - "roles/system"

- name: install mongo db v24
  hosts: "{{ server_group_name }}"
  vars:
    os_flavor: "rhel"
    mongo_major_version: "v24"
    mongo_full_version: "2.4.6"
    replicaset_name: "{{ server_group_name }}"
  roles: 
    - "roles/mongod"
